title: Tianyao Su's Homepage
page-top-title: Tianyao Su （苏天尧）
top-section-bg-text: Computer Science & Artificial Intelligence
home-subtitle: Tianyao Su&ensp;|&ensp;苏天尧
copyright-text: '&copy; Tianyao Su 2025-2026. All Rights Reserved.'
